### ISSUE TITLE
Add summary.md for demo sidebar

### ISSUE THREAD

**Issue by lc-soft** [lc-ui/lcui.css#1]

**Comment by zjh-nuc-AIOT** [comment]
如何展示一张图片啊，我现在做的事加载到css里，有没有直接在xml中导入的方法

**Comment by lc-soft** [comment]
@zjh-nuc-AIOT 为什么不点击 ![image](https://user-images.githubusercontent.com/1730073/103732188-df929300-5021-11eb-8c80-8ac229655b1e.png)  按钮提交问题？是为了节省写标题的时间吗？

**Comment by lc-soft** [comment]
> 如何展示一张图片啊，我现在做的事加载到css里，有没有直接在xml中导入的方法

css 引用图片文件路径，参考：

https://github.com/lc-soft/LCUI/blob/345031d74ca65225ec3623e0c92d448f54f5052b/test/test_scaling_support.css#L9-L16

注意，必须用 backgound-image 属性，用简写的 backgound 属性无效果。

**Comment by zjh-nuc-AIOT** [comment]
已经实现，感谢

**Comment by zjh-nuc-AIOT** [comment]
您好，我在用这个项目修改一下交了我们学校的课设项目。您能暂时把我列为浏览器那个例子的开发者吗？我怕老师不让用外部库。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lc-ui/lc-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月6日(星期三) 中午1:22
收件人:&nbsp;"lc-ui/lc-design"<lc-design@noreply.github.com&gt;;
抄送:&nbsp;"轻吻也飘然👄"<2633716446@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lc-ui/lc-design] Add summary.md for demo sidebar (#1)





 
@zjh-nuc-AIOT 为什么不点击   按钮提交问题？是为了节省写标题的时间吗？

**Comment by lc-soft** [comment]
> 您好，我在用这个项目修改一下交了我们学校的课设项目。您能暂时把我列为浏览器那个例子的开发者吗？我怕老师不让用外部库。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lc-ui/lc-design" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月6日(星期三) 中午1:22 收件人:&nbsp;"lc-ui/lc-design"<lc-design@noreply.github.com&gt;; 抄送:&nbsp;"轻吻也飘然"<2633716446@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [lc-ui/lc-design] Add summary.md for demo sidebar (#1) @zjh-nuc-AIOT 为什么不点击 按钮提交问题？是为了节省写标题的时间吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

不能。

是否可以理解为：你想基于网上找到的项目做点修改然后作为课设项目，但又怕老师因看出项目里的大部分功能都是别人写好的而拒绝，所以要求成为项目成员以让老师认为这项目是你参与开发的？

**Comment by zjh-nuc-AIOT** [comment]
我也感觉我这请求太沙雕了，我自己动手实现了下，感觉老师问些问题容回答上来就好了。还是感谢大佬的项目，以后多多学习。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lc-ui/lc-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月12日(星期二) 下午5:14
收件人:&nbsp;"lc-ui/lc-design"<lc-design@noreply.github.com&gt;;
抄送:&nbsp;"轻吻也飘然👄"<2633716446@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [lc-ui/lc-design] Add summary.md for demo sidebar (#1)





  
您好，我在用这个项目修改一下交了我们学校的课设项目。您能暂时把我列为浏览器那个例子的开发者吗？我怕老师不让用外部库。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lc-ui/lc-design" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月6日(星期三) 中午1:22 收件人:&nbsp;"lc-ui/lc-design"<lc-design@noreply.github.com&gt;; 抄送:&nbsp;"轻吻也飘然"<2633716446@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [lc-ui/lc-design] Add summary.md for demo sidebar (#1) @zjh-nuc-AIOT 为什么不点击 按钮提交问题？是为了节省写标题的时间吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
不能。
 
是否可以理解为：你想基于网上找到的项目做点修改然后作为课设项目，但又怕老师因看出项目里的大部分功能都是别人写好的而拒绝，所以要求成为项目成员以让老师认为这项目是你参与开发的？
